In [1]:
import numpy as np

### 1D Array

In [2]:
arr1 = np.array([1,2,3])

In [3]:
arr1

array([1, 2, 3])

### 2D Array

In [4]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [5]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

 ### 3D Array

In [6]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

####  3x3 array of zeros

In [8]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 3x5 array of ones

In [9]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### 4x6 array filled with 8

In [10]:
np.full((4,6), 8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

### 4x4 identity matrix

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### [1, 10, 28, 37] (like range)

In [12]:
np.arange(1,100, 9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

### [  1.  ,  25.75,  50.5 ,  75.25, 100.  ] (evenly spaced)

In [13]:
np.linspace(1,100, 5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [14]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [15]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [16]:
print("Shape:", myarr.shape)
print("Size:", myarr.size)
print("Dimensions:", myarr.ndim)
print("Data Type:", myarr.dtype)

Shape: (4, 3)
Size: 12
Dimensions: 2
Data Type: int64


In [17]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]], dtype='float32')

In [18]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 12., 13.]], dtype=float32)

In [19]:
myarr.astype('float64')

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 12., 13.]])

In [20]:
myarr.astype('int32')

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]], dtype=int32)

In [21]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [22]:
myarr.shape

(4, 3)

In [23]:
reshaped = myarr.reshape((3,4))

In [24]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 11, 12, 13]])

In [25]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [26]:
myarr.reshape((6,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 11],
       [12, 13]])

In [27]:
myarr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])