In [1]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [2]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [3]:
flat = arr.flatten()

In [4]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [5]:
flat[0]

np.int64(1)

In [6]:
flat[3:6]

array([4, 5, 6])

In [7]:
flat[:5] # same as 0:5

array([1, 2, 3, 4, 5])

In [8]:
flat[3:] # same as flat 0:13

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [9]:
flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [10]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [11]:
b = flat[3:7].copy() # This is not a slice because we are using copy method to get

In [12]:
b

array([4, 5, 6, 7])

In [13]:
b[0] = 44444444444666

In [14]:
b

array([44444444444666,              5,              6,              7])

In [15]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [16]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [17]:
arr[[1,4,6]]

array([2, 5, 7])

In [18]:
arr[arr>5]

array([6, 7, 8, 9])

## Exercises for Practice
~ Create a 3×3 array filled with random numbers and print its shape.

~ Convert an array of floats [1.1, 2.2, 3.3] into integers.

~ Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].

~ Reshape a 1D array of size 9 into a 3×3 matrix.

~ Use boolean masking to filter numbers greater than 50 in an array.

#### Create a 3×3 array filled with random numbers and print its shape.

In [19]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr1.shape

(3, 3)

#### Convert an array of floats [1.1, 2.2, 3.3] into integers.

In [22]:
arr2 = np.array([[1.1, 2.2, 3.3]])

In [23]:
arr2.astype('int')

array([[1, 2, 3]])

#### Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].

In [24]:
arr3 = np.array([1, 2, 3, 4, 5, 6])

In [25]:
idx = [1,3,5]

In [26]:
print(arr3[idx])

[2 4 6]


#### Reshape a 1D array of size 9 into a 3×3 matrix.

In [27]:
arr4 = np.array([1,2,3,4,5,6,7,8,9])

In [28]:
arr4.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Use boolean masking to filter numbers greater than 50 in an array.

In [29]:
arr5 = np.array([10,20,30,40,50,60,70,80,90,100])

In [30]:
mask = arr5 > 50

In [31]:
print(arr5[mask])

[ 60  70  80  90 100]
