In [1]:
import numpy as np
arr = np.array([[1, 2, 3], 
[4, 5, 6], 
[7, 8, 9]])

In [2]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr[0]

array([1, 2, 3])

In [4]:
arr[1]

array([4, 5, 6])

###### Sum along rows (down each column)

In [5]:
 np.sum(arr, axis = 0)

array([12, 15, 18])

###### Sum along columns (across each row)

In [6]:
 np.sum(arr, axis = 1)

array([ 6, 15, 24])

In [7]:
arr[0][1]

np.int64(2)