# Built in Mathematical functions in Numpy
Here are some common NumPy methods that are frequently used for statistical and mathematical operations:

1. **`np.mean()`** – Compute the **mean** (average) of an array.
   ```python
   np.mean(arr)
   ```

2. **`np.std()`** – Compute the **standard deviation** of an array.
   ```python
   np.std(arr)
   ```

3. **`np.var()`** – Compute the **variance** of an array.
   ```python
   np.var(arr)
   ```

4. **`np.min()`** – Compute the **minimum** value of an array.
   ```python
   np.min(arr)
   ```

5. **`np.max()`** – Compute the **maximum** value of an array.
   ```python
   np.max(arr)
   ```

6. **`np.sum()`** – Compute the **sum** of all elements in an array.
   ```python
   np.sum(arr)
   ```

7. **`np.prod()`** – Compute the **product** of all elements in an array.
   ```python
   np.prod(arr)
   ```

8. **`np.median()`** – Compute the **median** of an array.
   ```python
   np.median(arr)
   ```

9. **`np.percentile()`** – Compute the **percentile** of an array.
   ```python
   np.percentile(arr, 50)  # For the 50th percentile (median)
   ```

10. **`np.argmin()`** – Return the **index of the minimum** value in an array.
    ```python
    np.argmin(arr)
    ```

11. **`np.argmax()`** – Return the **index of the maximum** value in an array.
    ```python
    np.argmax(arr)
    ```

12. **`np.corrcoef()`** – Compute the **correlation coefficient** matrix of two arrays.
    ```python
    np.corrcoef(arr1, arr2)
    ```

13. **`np.unique()`** – Find the **unique elements** of an array.
    ```python
    np.unique(arr)
    ```

14. **`np.diff()`** – Compute the **n-th differences** of an array.
    ```python
    np.diff(arr)
    ```

15. **`np.cumsum()`** – Compute the **cumulative sum** of an array.
    ```python
    np.cumsum(arr)
    ```

16. **`np.linspace()`** – Create an array with **evenly spaced numbers** over a specified interval.
    ```python
    np.linspace(0, 10, 5)  # 5 numbers from 0 to 10
    ```

17. **`np.log()`** – Compute the **natural logarithm** of an array.
    ```python
    np.log(arr)
    ```

18. **`np.exp()`** – Compute the **exponential** of an array.
    ```python
    np.exp(arr)
    ```

These methods are used for performing mathematical and statistical operations with NumPy

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6])

In [3]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([15, 25, 35, 45, 55])

In [4]:
np.mean(arr)

np.float64(3.5)

In [5]:
np.std(arr)

np.float64(1.707825127659933)

In [6]:
np.var(arr)

np.float64(2.9166666666666665)

In [7]:
np.min(arr)

np.int64(1)

In [8]:
np.max(arr)

np.int64(6)

In [9]:
np.sum(arr)

np.int64(21)

In [10]:
np.prod(arr)

np.int64(720)

In [11]:
np.median(arr)

np.float64(3.5)

In [12]:
np.percentile(arr, 50)

np.float64(3.5)

In [13]:
np.argmin(arr)

np.int64(0)

In [14]:
np.argmax(arr)

np.int64(5)

In [15]:
np.corrcoef(arr1, arr2)

array([[1., 1.],
       [1., 1.]])

In [16]:
np.unique(arr)

array([1, 2, 3, 4, 5, 6])

In [17]:
np.diff(arr)

array([1, 1, 1, 1, 1])

In [18]:
np.cumsum(arr)

array([ 1,  3,  6, 10, 15, 21])

In [19]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947])

In [21]:
np.exp(arr)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 , 403.42879349])